[package]
name = "rcm-rs"
version = "0.1.0"
authors = ["Thejaswi Kadur <thejas.kadur@gmail.com>"]
edition = "2018"

[dependencies]
gethostname = "*"
dirs = "*"
serde = { version = "*", features = ["derive"] }
toml = "*"
derive_more = "*"