unstable_features = true

combine_control_expr = false
error_on_line_overflow = true
format_code_in_doc_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
wrap_comments = true