unstable_features = true

error_on_line_overflow = true
combine_control_expr = false
format_strings = true
merge_imports = true
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
format_code_in_doc_comments = true
wrap_comments = true