name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose